openapi: 3.1.0
info:
  title: Snake Charmer Plugin
  description: A plugin that allows the user to perform functions in a Python environment.
  version: "v1"
servers:
  - url: https://snake-charmer.azurewebsites.net
paths:
  /dataframe-chat:
    post:
      operationId: dataframe-chat
      description: |
        Execute the native dataframe-chat function; submit the file path and prompt as a JSON object in the payload input, e.g. {"file_loc": "<URL OF FILE TO CHAT WITH>", "prompt": "<PROMPT TO EXECUTE AGAINST FILE>"}
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/dataframe-chat"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    dataframe-chat:
      type: object
      properties:
        file_loc:
          type: string
        prompt:
          type: string
      required:
        - input
