openapi: 3.1.0
info:
  title: Snake Charmer Plugin
  description: A plugin that allows the user to perform functions in a Python environment.
  version: "v1"
servers:
  - url: https://snake-charmer.azurewebsites.net
paths:
  /dataframe-chat:
    post:
      operationId: dataframe-chat
      description: |
        Execute a prompt using a native dataframe-chat function against a remote data source containing inventory . Send the prompt as a JSON object in the payload. e.g. {"prompt": "<PROMPT TO EXECUTE>"}
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/dataframe-chat"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    dataframe-chat:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: The prompt to execute against the remote data source.
          required: true
